# Example: Docker Compose Stack
# Copy this to apps/<your-subdomain>/provision.yaml

apiVersion: provisioner.quickable.co/v1
kind: ComposeStack
metadata:
  # Your subdomain: will become https://my-stack.apps.quickable.co
  name: my-stack

  # Brief description (optional)
  description: "A multi-service application with web frontend and database"

  # Your GitHub username (required for contact/ownership)
  maintainer: "@your-github-username"

spec:
  # Source configuration
  source:
    type: github
    github:
      owner: "your-org"
      repo: "your-stack-repo"
      branch: "main"
      composePath: "docker-compose.prod.yaml"  # Path to compose file

  # Resource allocation for the entire stack
  resources:
    size: M  # Medium resources for multi-service apps

  # Environment variables (applied to all services)
  env:
    NODE_ENV: "production"
    PUBLIC_URL: "https://my-stack.apps.quickable.co"

    # Reference secrets for sensitive values
    secretRefs:
      - name: POSTGRES_PASSWORD
        secret: MY_STACK_DB_PASSWORD
      - name: REDIS_URL
        secret: MY_STACK_REDIS_URL

  # Ingress: which service receives public traffic
  ingress:
    service: web      # Service name from docker-compose.yaml
    port: 80          # Port the service exposes

  # Auto-deploy on source changes (default: true)
  autoDeploy: true

# ---------------------------------------------------------
# Example docker-compose.prod.yaml in your repo:
# ---------------------------------------------------------
#
# version: "3.8"
#
# services:
#   web:
#     build: ./web
#     ports:
#       - "80:80"
#     environment:
#       - DATABASE_URL=postgres://db:5432/app
#       - REDIS_URL=${REDIS_URL}
#     depends_on:
#       - db
#       - redis
#
#   db:
#     image: postgres:15-alpine
#     environment:
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#
#   redis:
#     image: redis:7-alpine
#
# volumes:
#   pgdata:
